spotify/Dockerfile

Updates the Spotifyd daemon to the latest release: https://github.com/Spotifyd/spotifyd/releases/tag/v0.2.3
**NA**
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

⬆️ Upgrades Spotifyd daemon to v0.2.3

---

LICENSE.md
README.md
spotify/.README.j2
spotify/DOCS.md

Happy New Year

---

spotify/Dockerfile
spotify/build.json

Upgrades add-on base image to v10.0.0

⬆️ Upgrades add-on base image to v10.0.0

---

spotify/Dockerfile

⬆️ Upgrades cargo to 1.52.1-r1

---

spotify/Dockerfile
spotify/build.json

Upgrades add-on base image to v10.0.1

⬆️ Upgrades add-on base image to v10.0.1

---

spotify/Dockerfile
spotify/build.yaml

Upgrades add-on base image to 10.2.2

⬆️ Upgrades add-on base image to 10.2.2

---

spotify/Dockerfile

https://github.com/librespot-org/librespot/releases/tag/v0.3.0
https://github.com/librespot-org/librespot/releases/tag/v0.3.1

⬆️ Upgrades librespot to 0.3.1

---

spotify/Dockerfile
spotify/build.yaml

Upgrades add-on base image to 11.0.0

⬆️ Upgrades add-on base image to 11.0.0

---

spotify/translations/hu.yaml

> Created the `hu.yaml` file, to have a Hungarian translation.
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

Added Hungarian translation

---

LICENSE.md
README.md
spotify/.README.j2
spotify/DOCS.md

:fireworks: Updates maintenance/license year to 2022

---

spotify/Dockerfile
spotify/build.yaml

Upgrades add-on base image to 11.0.1

⬆️ Upgrades add-on base image to 11.0.1

---

spotify/Dockerfile
spotify/build.yaml

Upgrades add-on base image to 11.1.0

⬆️ Upgrades add-on base image to 11.1.0

---

.github/workflows/deploy.yaml
spotify/build.yaml
spotify/config.yaml

Sign add-on with Codenotary Community Attestation Service (CAS)

:lock: Sign add-on with Codenotary Community Attestation Service (CAS)

---

spotify/DOCS.md

To make it easier to find the add-on.

:books: Add My buttons to documentation

---

spotify/Dockerfile

⬆️ Upgrades git to 2.34.2-r0

---

spotify/Dockerfile

https://github.com/librespot-org/librespot/releases/tag/v0.4.1

⬆️ Upgrades librespot to 0.4.1

---

spotify/Dockerfile

Not sure what happened there, but... this cleans it up :)

:broom: Clean up unneeded command line params

---

spotify/translations/it.yaml

maybe there will be some issues with the apostrophe.
> Added it.yaml to provide an italian translation

Create it.yaml (italian translation)

---

spotify/translations/it.yaml

removed stuff still written in english

🌎 Italian translation updates

---

spotify/Dockerfile
spotify/build.yaml

⬆️ Upgrades add-on base image to 12.2.1

---

spotify/Dockerfile
spotify/build.yaml

⬆️ Upgrades add-on base image to 12.2.2

---

spotify/Dockerfile

Changelog upstream: <https://github.com/librespot-org/librespot/releases/tag/v0.4.2>
It seems to still work for me locally.
- fixes #182
- fixes #171

⬆️ Upgrades librespot to 0.4.2

---

spotify/Dockerfile
spotify/build.yaml

Upgrades add-on base image to 12.2.3

⬆️ Upgrades add-on base image to 12.2.3

---

spotify/Dockerfile
spotify/build.yaml

⬆️ Upgrades add-on base image to 12.2.7

---

spotify/Dockerfile
spotify/build.yaml

Upgrades the add-on base image, which is now based on Alpine Linux 3.17

⬆️ Upgrades add-on base image to 13.0.0

---

LICENSE.md
README.md
spotify/.README.j2
spotify/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

.github/dependabot.yaml
.github/renovate.json
spotify/Dockerfile

Add Renovate for dependency management

---

README.md
spotify/build.yaml
spotify/config.yaml

Drop support for i386

---

LICENSE.md
README.md
spotify/.README.j2
spotify/DOCS.md

:fireworks: Updates maintenance/license year to 2024
